//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempleTemplate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TempleTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CenterJustify {
            get {
                object obj = ResourceManager.GetObject("CenterJustify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///        &lt;div id=&quot;closing&quot;&gt;.
        /// </summary>
        internal static string closing1 {
            get {
                return ResourceManager.GetString("closing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string closing2 {
            get {
                return ResourceManager.GetString("closing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///        &lt;div style=&quot;display: inline-block;
        ///                    width: 100%;&quot;&gt;
        ///            &lt;div id=&quot;event-heading&quot;
        ///                 style=&quot;background: linear-gradient(to right, rgba(162, 50, 4, 1), rgba(162, 50, 4, 0));
        ///                        padding: 5px;&quot;&gt;
        ///                &lt;h2&gt;.
        /// </summary>
        internal static string event1 {
            get {
                return ResourceManager.GetString("event1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h2&gt;
        ///            &lt;/div&gt;
        ///            &lt;div style=&quot;float: left;
        ///                        padding: 5px 5px 0px 0px&quot;&gt;
        ///                &lt;img id=&quot;event-img&quot;
        ///                     src=&quot;.
        /// </summary>
        internal static string event2 {
            get {
                return ResourceManager.GetString("event2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;
        ///                     style=&quot;width: 150px;&quot; /&gt;
        ///            &lt;/div&gt;
        ///            &lt;div id=&quot;event-text&quot;
        ///                 style=&quot;padding: 5px;
        ///                 float: left;
        ///                 width: 600px;&quot;&gt;.
        /// </summary>
        internal static string event3 {
            get {
                return ResourceManager.GetString("event3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///        &lt;/div&gt;
        ///        &lt;br /&gt;.
        /// </summary>
        internal static string event4 {
            get {
                return ResourceManager.GetString("event4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_bgcolor {
            get {
                object obj = ResourceManager.GetObject("font_bgcolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_bold {
            get {
                object obj = ResourceManager.GetObject("font_bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_fgcolor {
            get {
                object obj = ResourceManager.GetObject("font_fgcolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_italic {
            get {
                object obj = ResourceManager.GetObject("font_italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_strike {
            get {
                object obj = ResourceManager.GetObject("font_strike", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_underline {
            get {
                object obj = ResourceManager.GetObject("font_underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Bharatiya Temple of Lansing Newsletter&lt;/title&gt;
        ///
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial;
        ///            width: 800px;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div&gt;
        ///        &lt;img src=&quot;http://lansingtemple.org/images/btl_lansing.jpg&quot; /&gt;
        ///        &lt;div id=&quot;news-date&quot;
        ///             style=&quot;background-color: rgba(162, 50, 4, 1);
        ///                    color: white;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string head1 {
            get {
                return ResourceManager.GetString("head1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LeftJustify {
            get {
                object obj = ResourceManager.GetObject("LeftJustify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paragraph_bullet {
            get {
                object obj = ResourceManager.GetObject("paragraph_bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paragraph_numbered {
            get {
                object obj = ResourceManager.GetObject("paragraph_numbered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;
        ///        &lt;br /&gt;
        ///        &lt;div id=&quot;pretext&quot;&gt;.
        /// </summary>
        internal static string pretext1 {
            get {
                return ResourceManager.GetString("pretext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/div&gt;.
        /// </summary>
        internal static string pretext2 {
            get {
                return ResourceManager.GetString("pretext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RightJustify {
            get {
                object obj = ResourceManager.GetObject("RightJustify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RtfToHtml {
            get {
                object obj = ResourceManager.GetObject("RtfToHtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
